### ISSUE TITLE
'sample sourceips' better as unique/distinct source ips?

### ISSUE THREAD

**Issue by floatingatoll** [jeffbryner/MozDef#174]
For certain alerts, a list of sample sourceips that triggered the alert is provided. In every case I've personally witnessed in production use, this is always the same IP repeated 3 times.

I think 'sample sourceips' should list *unique* source IPs that triggered the alert, rather than the first three IPs no matter what they are. If more than one IP is listed, the alert detail page will be much more useful than the IRC can be, and when only one IP is listed (the seemingly-common case), the IRC alert is sufficient without a clickthrough required.

**Comment by jeffbryner** [comment]
I've added a function to summarize a python dictionary by the most common terms and it's in use in most of the alerts, but not all. I'll see about getting that into all alerts for this release.

**Comment by jeffbryner** [comment]
OK, I think I've got them all converted.
