### ISSUE TITLE
Documentation for local accounts

### ISSUE THREAD

**Issue by kinomakino** [jeffbryner/MozDef#242]
First, thanks for the help and the work.

I am trying to mount Mozdef a debian and I'm going crazy with the installation process.
I managed to install everything by Docker, although the installation manual on is not clear, at least to those who have never used Docker.

I have a question about documentation.

For example, I want to login the IP it by going around 3000 but not how PERSON disable and enable a local account. Following the manual tells me that I must enter Meteor and make some commands ...

     From the meteor mozdef run directory '$ meteor remove mrt: accounts-person'
     'Meteor add accounts-password'
     Alter app / server / mozdef.js Accounts.config section to: forbidClientAccountCreation: false,
     restart Meteor

There is a slightly more detailed manual, or actually it's so complex?

Thank You !!!!

**Comment by jeffbryner** [comment]
Hey, thanks for taking it for a spin. 

Sorry about the confusion, let me see if I can clarify and use this opportunity to clean up the docs. 

Let me know if there are parts of the docker how-to that could be changed to be easier to understand. 

As for the login. meteor ships with a bunch of options for how to login but unfortunately all of them require some additional tweaking. I'm noticing the docs that worked for meteor .91 don't quite get local accounts working for current meteor 1.0.3 so let me do some tweaking of the code and docs.

**Comment by jeffbryner** [comment]
OK, I made some changes to the code and especially to the docker configuration to allow for easier transition to local accounts. 

Specifically, https://github.com/jeffbryner/MozDef/blob/master/docker/Dockerfile#L65  is a docker command to copy a css file into the working meteor that allows the local accounts UI controls to display. 

The end result is that you get a choice of using persona or local accounts without having to reconfigure any meteor code. 

Do you mind trying it out? I rebuilt the http://demo.mozdef.com:3000 site using it and it works fine there, you can login with local or persona and access the system.

**Comment by jeffbryner** [comment]
Closing this as 'works for me', feel free to re-open if this doesn't satisfy the issue.
