### ISSUE TITLE
healthAndStatus should allow more granular notifications

### ISSUE THREAD

**Issue by mpurzynski** [jeffbryner/MozDef#250]
The current healthAndStatus script does excellent job for monitoring if events from category A are still flowing.

I'd like to have it alert for every host that does not send N events of category CAT in M minutes. That would be very useful for the NSM, to monitor if every sensor sends data and not just 'something in Bro category' does.

I can (on my end) create kind of an internal "cron" job in Bro to periodically output a status message saying "i am still alive". If this script would not see it from every preconfigured sensor in the last 15 minutes, it will let us know.

**Comment by jeffbryner** [comment]
Implementing this as a deadman alert: i.e. a search that should return records and alert if it doesn't.
