### ISSUE TITLE
Alerts: searchEventsAggreg is limited to aggregations on fields in the 'details'

### ISSUE THREAD

**Issue by jeffbryner** [jeffbryner/MozDef#275]
https://github.com/jeffbryner/MozDef/blob/master/alerts/lib/alerttask.py#L321 expects the user to want to only aggregate on fields within the 'details' structure defined in the mozdef json standard: 
http://mozdef.readthedocs.org/en/latest/usage.html#json-format

This causes some issues with emerging JSON event formats such as cloudtrail or google api event logs that don't follow any event standard. The user is left to either massage the data into 'mozdef format' or modify the alert code to generate alerts. 

Alter the function to accept an aggregationPath instead of field that can be a dotted dict style specifier: details.subfield.subfield for example. This would also allow alerting on fields not under the details sub section, or on fields that don't follow the mozdef spec.

**Comment by jeffbryner** [comment]
FWIW I've got a prototype of a function to retrieve a dict key by dotted string path::

```python
def get_dict_path(input_dict, path_string):
    """
        Gets data from a dictionary using a dotted accessor-string
        http://stackoverflow.com/a/7534478
        path_string can be key.subkey.subkey.subkey
    """
    return_data = input_dict
    for chunk in path_string.split('.'):
        return_data = return_data.get(chunk, {})
    return return_data
```

**Comment by jeffbryner** [comment]
Labeled breaking since this will break existing alerts that assume they are being aggregated at the details.subfield level by default

**Comment by h2ko** [comment]
I have a fix for this that retains the functionality of the original, but you can manually call a dot path as an option:

https://github.com/h2ko/MozDef/blob/master/alerts/lib/alerttask.py

**Comment by jeffbryner** [comment]
Thanks. I think I'm going to also use this opportunity to fix up some names: Aggreg->Aggregation for example just to make sure it's consistent.
