### ISSUE TITLE
WebUI: Integration to external tools with a plugin system

### ISSUE THREAD

**Issue by netantho** [jeffbryner/MozDef#60]
Should have a plugin system to integrate external tools.

Tools examples:
- banhammer
- [banhammer-ng](https://github.com/mozilla/BanHammer)
- [mig](https://github.com/mozilla/mig)
- [inventory](https://github.com/mozilla/inventory)

Example of usage:
- Add a banhammer-ng link with MozDef alerts
- Button to launch mig investigation

**Comment by jeffbryner** [comment]
This is covered in the plugins interface for the REST API delivered in release v1.7. Banhammer, FXA queues implemented as plugins.
