### ISSUE TITLE
WebUI: links for supporting docs

### ISSUE THREAD

**Issue by netantho** [jeffbryner/MozDef#62]
Be able to reference external web documents used for an incident:
- google docs (writer, spreadsheet, slides)
- etherpad
- dropbox
- pastebin
- kibana
- bugzilla
- other links

**Comment by jeffbryner** [comment]
The incidents/references tab is a place for URLS now, but it's pretty basic. I'll set about adding recognition to the url scheme for just pasting in a link and having it figure out the destination to add some decoration/features/tooltips.
